# Generated by Django 3.2 on 2022-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_preview',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
