# Generated by Django 3.2 on 2022-08-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
